# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f21ae250e6830082180400662cff0bf7eabf07b13b458156b838452f30faf70b7acc9bd72d86bcee4b3bd0aa9129ff54e02d33dda58ac0ca3b335ae2e676b234

test:
  secret_key_base: 96a92de072193c7d73d1d99c216d58c9f53164a91147eac98de416a76f2c72ab615ce96eafaed4c56457a6bf51e3ca1787674b51e70504d44e78f6b4a85d15eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
